backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - {
              label: Featured Images,
              name: featuredImages,
              widget: list,
              allow_add: false,
              fields:
                [
                  { label: Image, name: image, widget: image },
                  { label: Caption, name: caption, widget: string },
                  {
                    label: "Secondary Caption",
                    name: secondaryCaption,
                    widget: string,
                  },
                ],
            }
      - file: "src/pages/about/index.md"
        label: About
        name: about
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Body, name: body, widget: markdown }
      - file: "src/pages/portfolio/index.md"
        label: Portfolio
        name: portfolio
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "portfolio-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "title", widget: "string" }
          - {
              label: Items,
              name: items,
              widget: list,
              fields:
                [
                  { label: Image, name: image, widget: image },
                  { label: Date, name: date, widget: datetime },
                  { label: Tags, name: tags, widget: list },
                ],
            }
